apiVersion: v2
name: kms
description: A Helm chart for kms
type: application
version: 1.0.0
keywords:
  - kms
sources:
  - https://github.com/erda-project/erda-release
maintainers:
  - name: Luobingli
    email: luobily@gmail.com
  - name: Wangzhuzhen
    email: zhuzhenwang1984@gmail.com
  - name: Liutianxiang
    email: root@viper.run
