redisOperator:
  name: redis-operator
  version: 1.0.0-20200723-1a7a9f14
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:

redisFailover:
  name: addon-redis
  version: 3.2.12
  secret: aUVWSUk2TFk2RWJyYzRIWA==
  redis:
    replicas: 1
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu:
        memory: