sonar:
  name: addon-sonar
  version: 8.4.2
  token: LY9DepZ7iDUsyH8TFoDR85ok7y2nw1
  password: 78tE846484lQQFUwY51h0Yr96ZQ063
  ingressHost: sonar.${ERDA_GENERIC_DOMAIN}
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory: