kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: volume-provisioner
  name: erda-volume-provisioner
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  selector:
    matchLabels:
      app: volume-provisioner
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: erda-volume-provisioner
      labels:
        app: volume-provisioner
    spec:
      serviceAccountName: erda-volume-provisioner
      containers:
        - image:
            {{ .Values.global.image.repository }}/volume-provisioner:{{ .Values.tag }}
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: PROVISIONER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LOCAL_PROVISIONER_NAME
            value: dice/local-volume
          - name: NET_PROVISIONER_NAME
            value: dice/netdata-volume
          imagePullPolicy: Always
          name: volume-provisioner
          volumeMounts:
            - name: host-dir
              mountPath: /hostfs
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "10m" | quote }}
              memory: {{ .Values.resources.requests.memory | default "10Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "100m" | quote }}
              memory: {{ .Values.resources.limits.memory | default "256Mi" | quote }}
      volumes:
        - name: host-dir
          hostPath:
            path: /
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
        - operator: Exists


