namespace: ${ERDA_NAMESPACE}

image:
  repository: registry.erda.cloud/erda
  imagePullPolicy: IfNotPresent
  

redisOperator:
  name: redis-operator
  version: 1.0.0-20200723-1a7a9f14
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:

cassandraOperator:
  name: cassandra-operator
  version: v1.1.3-release
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:

elasticsearchOperator:
  name: elasticsearch-operator
  version: 1.0.1

erdaOperator:
  name: erda-operator
  version: 1.0.0-20210427-3d25066

configmap:
  size: demo
  clustername: ${ERDA_CLUSTER_NAME}
  domain: ${ERDA_GENERIC_DOMAIN}
  protocol: http

  ssh:
    user: root
    password: ""

  kubernetes:
    version: 1.18.8
    master: ${KUBERNETES_MASTERIP}
    mastervip: ${KUBERNETES_APISERVERVIP}
    lb:

volumeProvisoner:
  name: volume-provisioner
  version: 1.0.0-20210416-1a3758f
  provisioner:
    local: dice/local-volume
    nfs: dice/netdata-volume
  storageclass:
    local: dice-local-volume
    nfs: dice-nfs-volume
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory: 
