apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "addon-kms" }}
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
    - name: http
      port: 3082
      protocol: TCP
      targetPort: 3082
  selector:
    app.kubernetes.io/name: kms
