apiVersion: v1
data:
  common-config.yml: |
    thread_pool.bulk.queue_size: 1000
    thread_pool.index.queue_size: 1000
    thread_pool.index.size: 3
kind: ConfigMap
metadata:
  name: erda-elasticsearch-config
  namespace: {{ .Release.Namespace }}