apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    dice/addon: erda-elasticsearch
    erda/addon: erda-elasticsearch
  name: erda-elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: OrderedReady
  {{- if eq .Values.global.size "demo" }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.replicas | default 3 }}
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      dice/addon: erda-elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        dice/addon: erda-elasticsearch
    spec:
      affinity:
        {{- if ne .Values.global.size "demo" }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "dice/platform"
                operator: Exists
              - key: "dice/elasticsearch"
                operator: Exists
        {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: erda/addon
                operator: In
                values:
                - erda-elasticsearch
            topologyKey: "kubernetes.io/hostname"
      containers:
        - env:
            - name: CLUSTER_NAME
              value: erda-elasticsearch
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: erda-elasticsearch-master
            - name: SSL_ENABLE
              value: "false"
            - name: KEY_PASS
              valueFrom:
                secretKeyRef:
                  key: key_pass
                  name: erda-elasticsearch-cert
            - name: NUMBER_OF_MASTERS
              {{- if eq .Values.global.size "demo" }}
              value: "1"
              {{- else }}
              value: {{ .Values.numberOfMasters | default "2" | quote }}
              {{- end }}
            - name: MODE
              value: client
            - name: ES_JAVA_OPTS
              {{- if eq .Values.global.size "demo" }}
              value: {{ .Values.javaOpts | default "-Xms1024m -Xmx1024m" | quote }}
              {{- else }}
              value: {{ .Values.javaOpts | default "-Xms6144m -Xmx6144m" | quote }}
              {{- end }}
            - name: SEARCHGUARD_DISABLED
              value: "true"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image:  {{ .Values.global.image.repository }}/addon-elasticsearch:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
          livenessProbe:
            failureThreshold: 9
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          name: elasticsearch
          ports:
            - containerPort: 9300
              name: transport
              protocol: TCP
            - containerPort: 9200
              name: http
              protocol: TCP
          resources:
            {{- if eq .Values.global.size "demo" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu| default "200m" | quote }}
              memory: {{ .Values.resources.requests.memory | default "512Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "1" | quote }}
              memory: {{ .Values.resources.limits.memory | default "3096Mi" }}
            {{- else }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "2" | quote }}
              memory: {{ .Values.resources.requests.memory | default "4Gi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "4" | quote }}
              memory: {{ .Values.resources.limits.memory | default "12Gi" | quote }}
            {{- end }}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /elasticsearch/custom-config
              name: custom-config
            - mountPath: /elasticsearch/plugins/search-guard-6/sgconfig
              name: sgconfig
            - mountPath: /elasticsearch/config/certs
              name: certs
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: temp
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          image: registry.erda.cloud/erda/kubedb-busybox:1.0.0
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          resources:
            {{- if eq .Values.global.size "demo" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "100m" | quote }}
              memory: {{ .Values.resources.requests.memory | default "512Mi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" | quote }}
              memory: {{ .Values.resources.limits.memory | default "2048Mi" }}
            {{- else }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "1" | quote }}
              memory: {{ .Values.resources.requests.memory | default "4Gi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "2" | quote }}
              memory: {{ .Values.resources.limits.memory | default "8Gi" | quote }}
            {{- end }}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: erda-elasticsearch
      serviceAccountName: erda-elasticsearch
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: erda-elasticsearch-config
          name: custom-config
        - name: sgconfig
          secret:
            defaultMode: 420
            secretName: erda-elasticsearch-auth
        - name: certs
          secret:
            defaultMode: 420
            items:
              - key: root.jks
                path: root.jks
              - key: node.jks
                path: node.jks
              - key: sgadmin.jks
                path: sgadmin.jks
            secretName: erda-elasticsearch-cert
        - emptyDir: {}
          name: temp
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: elasticsearchcluster
        app.kubernetes.io/managed-by: Helm
        dice/addon: erda-elasticsearch
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          {{- if eq .Values.global.size "demo" }}
          storage: {{ .Values.capacity | default "50Gi" }}
          {{- else }}
          storage: {{ .Values.capacity | default "1000Gi" }}
          {{- end }}
      storageClassName: {{ .Values.storageClassName | default "dice-local-volume" }}
      volumeMode: Filesystem
