{{- if eq .Values.global.size "demo" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: erda-zookeeper
  name: erda-zookeeper
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erda-zookeeper
  serviceName: erda-zookeeper
  template:
    metadata:
      labels:
        app: erda-zookeeper
    spec:
      tolerations:
        - operator: Exists
      {{- if .Values.nodematchExpressions }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                {{- range $_, $value := .Values.nodematchExpressions }}
                  - key: {{ $value.key }}
                    operator: {{ $value.operator }}
                {{- end }}
      {{- end }}
      containers:
        - name: erda-zookeeper
          image: {{ .Values.global.image.repository }}/addon-zookeeper:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy  | default "IfNotPresent" }}
          ports:
          - containerPort: 2181
            protocol: TCP
          - containerPort: 2888
            protocol: TCP
          - containerPort: 3888
            protocol: TCP
          env:
          - name: DICE_PLATFORM_ADDON
            value: erda-zookeeper
          - name: ZOO_AUTO_INTERVAL
            value: '2'
          - name: ZOO_AUTO_RETAINCOUNT
            value: '3'
          - name: ZOO_CONF_DIR
            value: "/conf"
          - name: ZOO_DATA_DIR
            value: "/data"
          - name: ZOO_DATA_LOG_DIR
            value: "/datalog"
          - name: ZOO_INIT_LIMIT
            value: '5'
          - name: ZOO_MAX_CLIENT_CNXNS
            value: '60'
          - name: ZOO_MY_ID
            value: '1'
          - name: ZOO_PORT
            value: '2181'
          - name: ZOO_SYNC_LIMIT
            value: '2'
          - name: ZOO_TICK_TIME
            value: '6000'
          - name: ZOO_USER
            value: zookeeper
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "0.1" | quote }}
              memory: {{ .Values.resources.requests.memory | default "10Mi" | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu |  default "1" | quote }}
              memory: {{ .Values.resources.limits.memory | default "400Mi" | quote }}
          volumeMounts:
          - name: erda-zookeeper
            mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 9
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: erda-zookeeper
      name: erda-zookeeper
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.capacity | default "32Gi" }}
      storageClassName: {{ .Values.global.storageClassName | default "dice-local-volume" }}
      volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: erda-zookeeper
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  ports:
  - name: erda-zookeeper-tcp-2181
    protocol: TCP
    port: 2181
  - name: erda-zookeeper-tcp-2888
    protocol: TCP
    port: 2888
  - name: erda-zookeeper-tcp-3888
    protocol: TCP
    port: 3888
  selector:
    app: erda-zookeeper
{{- end }}
