apiVersion: apps/v1
kind: Deployment
metadata:
  name: erda-cassandra-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app:  erda-cassandra-operator
    operator: erda-cassandra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  erda-cassandra-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0%
  template:
    metadata:
      labels:
        name: erda-cassandra-operator
        app: erda-cassandra-operator
        operator: erda-cassandra-operator
    spec:
      {{- if .Values.global.imagePullSecrets }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: erda-cassandra-operator
      securityContext:
        runAsUser: 1000
      tolerations:
        - operator: Exists
      containers:
      - name:  erda-cassandra-operator
        image: {{ .Values.global.image.repository }}/cassandra-operator:{{ .Values.operatorImageTag }}
        imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
        command:
        - casskop
        readinessProbe:
          exec:
            command:
            - /health
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 512Mi
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value:  "erda-cassandra-operator"
        - name: LOG_LEVEL
          value: Debug
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
