kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: erda-cassandra-operator
  annotations:
    "helm.sh/hook": pre-install
  name: erda-cassandra-operator
  namespace: {{ .Values.global.namespace | default "erda-system" }}
subjects:
- kind: ServiceAccount
  name: erda-cassandra-operator
  namespace: {{ .Values.global.namespace | default "erda-system" }}
roleRef:
  kind: Role
  name: erda-cassandra-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: erda-cassandra-operator
  annotations:
    "helm.sh/hook": pre-install
  name: erda-cassandra-cluster-node
  namespace: {{ .Values.global.namespace | default "erda-system" }}
subjects:
  - kind: ServiceAccount
    name: erda-cassandra-cluster-node
    namespace: {{ .Values.global.namespace | default "erda-system" }}
roleRef:
  kind: Role
  name: erda-cassandra-cluster-node
  apiGroup: rbac.authorization.k8s.io
