apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: erda-redis
  namespace: {{ .Values.global.namespace | default "erda-system" }}
spec:
  sentinel:
    image: {{ .Values.global.image.repository }}/addon-redis:{{ .Values.redisFailover.version }}
    {{- if eq .Values.global.size "prod" }}
    replicas: {{ .Values.redisFailover.sentinel.replicas | default 3 }}
    {{- else }}
    replicas: {{ .Values.redisFailover.sentinel.replicas | default 1 }}
    {{- end }}
    tolerations:
      - operator: Exists
    affinity:
      nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            {{- if .Values.nodematchExpressions }}
            {{- range $_, $value := .Values.nodematchExpressions }}
              - key: {{ $value.key }}
                operator: {{ $value.operator }}
            {{- end }}
            {{- end }}
    resources:
      requests:
        cpu: {{ .Values.redisFailover.sentinel.resources.requests.cpu | default "0.1" | quote }}
        memory: {{ .Values.redisFailover.sentinel.resources.requests.memory | default "10Mi" | quote }}
      limits:
        cpu: {{ .Values.redisFailover.sentinel.resources.requests.cpu | default ".2" | quote }}
        memory: {{ .Values.redisFailover.sentinel.resources.limits.memory | default "64Mi" | quote }}
    customConfig:
    - "down-after-milliseconds 12000"
    - "failover-timeout 12000"
  redis:
    image: {{ .Values.global.image.repository }}/addon-redis:{{ .Values.redisFailover.version }}
    {{- if eq .Values.global.size "prod" }}
    replicas: {{ .Values.redisFailover.redis.replicas | default 2 }}
    {{- else }}
    replicas: {{ .Values.redisFailover.redis.replicas | default 1 }}
    {{- end }}
    tolerations:
      - operator: Exists
    affinity:
      nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            {{- if .Values.nodematchExpressions }}
            {{- range $_, $value := .Values.nodematchExpressions }}
              - key: {{ $value.key }}
                operator: {{ $value.operator }}
            {{- end }}
            {{- end }}
    resources:
      requests:
        cpu: {{ .Values.redisFailover.redis.resources.requests.cpu | default "0.1" | quote }}
        memory: {{ .Values.redisFailover.redis.resources.requests.memory | default "10Mi" | quote }}
      limits:
        cpu: {{ .Values.redisFailover.redis.resources.requests.cpu | default ".3" | quote }}
        memory: {{ .Values.redisFailover.redis.resources.limits.memory | default "512Mi" | quote }}
  auth:
    secretPath: erda-redis-auth
