apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: erda-redis-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: erda-redis-operator
subjects:
- kind: ServiceAccount
  name: erda-redis-operator
  namespace: {{ .Release.Namespace }}