# 全局可用参数
global:
  # 部署模式：支持最小化单点部署（demo） 和 高可用部署（prod） 两种模式
  size: demo
  # 组件部署的目标 namespace，如果不存在需要先创建
  namespace: default
  # 镜像参数
  image:
    # 镜像仓库
    repository: registry.erda.cloud/erda
    # 镜像拉取策略
    imagePullPolicy: IfNotPresent
  # 镜像拉取 Secrets
  imagePullSecrets: [ ]


tag: 1.0.0-20210416-1a3758f
provisioner:
  local:
    hostpath: /data
  nfs:
    hostpath: /netdata
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"