apiVersion: v2
name: registry
description: A Helm chart for registry
type: application
version: 2.7.1
keywords:
  - registry
sources:
  - https://github.com/erda-project/erda-release
maintainers:
  - name: Luobingli
    email: luobily@gmail.com
  - name: Wangzhuzhen
    email: zhuzhenwang1984@gmail.com
  - name: Liutianxiang
    email: root@viper.run