# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # namespace defines which namespace will erda components deployed in Kubernetes.
  namespace: default
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]


# tag defines registry image tag.
tag: 2.7.1
# storageClassName defines which storageclass to use for creating PV in Kubernetes.
storageClassName: "dice-local-volume"
# capacity defines pvc capacity for registry instance (default: 1000Gi for prod mode and 50Gi for demo mode).
capacity:
# resources defines resources requests and limits for pod
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:
networkMode: ""
hostURL: ""
hostNode:

