# Global variable
global:
  # size defines deployment mode: 'demo' for minimal and 'prod' for product.
  size: demo
  # namespace defines which namespace will erda components deployed in Kubernetes.
  namespace: default
  # image defines repository and image pull policy for docker image.
  image:
    # repository defines docker image repository.
    repository: registry.erda.cloud/erda
    # imagePullPolicy defines how to pull images.
    imagePullPolicy: IfNotPresent
  # imagePullSecrets defines pull secrets for pulling image from private image repository.
  imagePullSecrets: [ ]

# tag defines kafka image tag.
tag: 1.1.0-20210323-be01a9b
# storageClassName defines which storageclass to use for creating PV in Kubernetes.
storageClassName: "dice-local-volume"
# capacity defines pvc capacity for kafka instance (default: 100Gi for prod mode and 16Gi for demo mode).
capacity:
# kafka JAVA_OPTS (java heap size suggests to set as 0.75 * resources.limits.memory. eg: "-Xmx6144m -Xms6144m" for resources.limits.memory is 8192Mi)
javaOpts:
# resources defines resources requests and limits for pod
resources:
  requests:
    cpu:
    memory:
  limits:
    cpu:
    memory:

